/**
 * @file audio.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/audio/audio.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>


namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, audio_format value) {
        switch (value) {
            case audio_format::unknown:
                return os << "unknown";
            case audio_format::u8:
                return os << "u8";
            case audio_format::s8:
                return os << "s8";
            case audio_format::s16le:
                return os << "s16le";
            case audio_format::s16be:
                return os << "s16be";
            case audio_format::s32le:
                return os << "s32le";
            case audio_format::s32be:
                return os << "s32be";
            case audio_format::f32le:
                return os << "f32le";
            case audio_format::f32be:
                return os << "f32be";
            default:
                return os << "Unknown_audio_format(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, audio_format& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <audio_format>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "unknown") {
            value = audio_format::unknown;
        } else if (str == "u8") {
            value = audio_format::u8;
        } else if (str == "s8") {
            value = audio_format::s8;
        } else if (str == "s16le") {
            value = audio_format::s16le;
        } else if (str == "s16be") {
            value = audio_format::s16be;
        } else if (str == "s32le") {
            value = audio_format::s32le;
        } else if (str == "s32be") {
            value = audio_format::s32be;
        } else if (str == "f32le") {
            value = audio_format::f32le;
        } else if (str == "f32be") {
            value = audio_format::f32be;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <audio_format>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
