/**
 * @file keyboard_codes.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/events/keyboard_codes.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <vector>
#include <unordered_map>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, scancode value) {
        switch (value) {
            case scancode::unknown:
                return os << "unknown";
            case scancode::a:
                return os << "a";
            case scancode::b:
                return os << "b";
            case scancode::c:
                return os << "c";
            case scancode::d:
                return os << "d";
            case scancode::e:
                return os << "e";
            case scancode::f:
                return os << "f";
            case scancode::g:
                return os << "g";
            case scancode::h:
                return os << "h";
            case scancode::i:
                return os << "i";
            case scancode::j:
                return os << "j";
            case scancode::k:
                return os << "k";
            case scancode::l:
                return os << "l";
            case scancode::m:
                return os << "m";
            case scancode::n:
                return os << "n";
            case scancode::o:
                return os << "o";
            case scancode::p:
                return os << "p";
            case scancode::q:
                return os << "q";
            case scancode::r:
                return os << "r";
            case scancode::s:
                return os << "s";
            case scancode::t:
                return os << "t";
            case scancode::u:
                return os << "u";
            case scancode::v:
                return os << "v";
            case scancode::w:
                return os << "w";
            case scancode::x:
                return os << "x";
            case scancode::y:
                return os << "y";
            case scancode::z:
                return os << "z";
            case scancode::num_1:
                return os << "num_1";
            case scancode::num_2:
                return os << "num_2";
            case scancode::num_3:
                return os << "num_3";
            case scancode::num_4:
                return os << "num_4";
            case scancode::num_5:
                return os << "num_5";
            case scancode::num_6:
                return os << "num_6";
            case scancode::num_7:
                return os << "num_7";
            case scancode::num_8:
                return os << "num_8";
            case scancode::num_9:
                return os << "num_9";
            case scancode::num_0:
                return os << "num_0";
            case scancode::f1:
                return os << "f1";
            case scancode::f2:
                return os << "f2";
            case scancode::f3:
                return os << "f3";
            case scancode::f4:
                return os << "f4";
            case scancode::f5:
                return os << "f5";
            case scancode::f6:
                return os << "f6";
            case scancode::f7:
                return os << "f7";
            case scancode::f8:
                return os << "f8";
            case scancode::f9:
                return os << "f9";
            case scancode::f10:
                return os << "f10";
            case scancode::f11:
                return os << "f11";
            case scancode::f12:
                return os << "f12";
            case scancode::f13:
                return os << "f13";
            case scancode::f14:
                return os << "f14";
            case scancode::f15:
                return os << "f15";
            case scancode::f16:
                return os << "f16";
            case scancode::f17:
                return os << "f17";
            case scancode::f18:
                return os << "f18";
            case scancode::f19:
                return os << "f19";
            case scancode::f20:
                return os << "f20";
            case scancode::f21:
                return os << "f21";
            case scancode::f22:
                return os << "f22";
            case scancode::f23:
                return os << "f23";
            case scancode::f24:
                return os << "f24";
            case scancode::return_key:
                return os << "return_key";
            case scancode::escape:
                return os << "escape";
            case scancode::backspace:
                return os << "backspace";
            case scancode::tab:
                return os << "tab";
            case scancode::space:
                return os << "space";
            case scancode::minus:
                return os << "minus";
            case scancode::equals:
                return os << "equals";
            case scancode::leftbracket:
                return os << "leftbracket";
            case scancode::rightbracket:
                return os << "rightbracket";
            case scancode::backslash:
                return os << "backslash";
            case scancode::nonushash:
                return os << "nonushash";
            case scancode::semicolon:
                return os << "semicolon";
            case scancode::apostrophe:
                return os << "apostrophe";
            case scancode::grave:
                return os << "grave";
            case scancode::comma:
                return os << "comma";
            case scancode::period:
                return os << "period";
            case scancode::slash:
                return os << "slash";
            case scancode::capslock:
                return os << "capslock";
            case scancode::scrolllock:
                return os << "scrolllock";
            case scancode::numlockclear:
                return os << "numlockclear";
            case scancode::printscreen:
                return os << "printscreen";
            case scancode::pause:
                return os << "pause";
            case scancode::insert:
                return os << "insert";
            case scancode::home:
                return os << "home";
            case scancode::pageup:
                return os << "pageup";
            case scancode::delete_key:
                return os << "delete_key";
            case scancode::end:
                return os << "end";
            case scancode::pagedown:
                return os << "pagedown";
            case scancode::right:
                return os << "right";
            case scancode::left:
                return os << "left";
            case scancode::down:
                return os << "down";
            case scancode::up:
                return os << "up";
            case scancode::kp_divide:
                return os << "kp_divide";
            case scancode::kp_multiply:
                return os << "kp_multiply";
            case scancode::kp_minus:
                return os << "kp_minus";
            case scancode::kp_plus:
                return os << "kp_plus";
            case scancode::kp_enter:
                return os << "kp_enter";
            case scancode::kp_1:
                return os << "kp_1";
            case scancode::kp_2:
                return os << "kp_2";
            case scancode::kp_3:
                return os << "kp_3";
            case scancode::kp_4:
                return os << "kp_4";
            case scancode::kp_5:
                return os << "kp_5";
            case scancode::kp_6:
                return os << "kp_6";
            case scancode::kp_7:
                return os << "kp_7";
            case scancode::kp_8:
                return os << "kp_8";
            case scancode::kp_9:
                return os << "kp_9";
            case scancode::kp_0:
                return os << "kp_0";
            case scancode::kp_period:
                return os << "kp_period";
            case scancode::lctrl:
                return os << "lctrl";
            case scancode::lshift:
                return os << "lshift";
            case scancode::lalt:
                return os << "lalt";
            case scancode::lgui:
                return os << "lgui";
            case scancode::rctrl:
                return os << "rctrl";
            case scancode::rshift:
                return os << "rshift";
            case scancode::ralt:
                return os << "ralt";
            case scancode::rgui:
                return os << "rgui";
            case scancode::application:
                return os << "application";
            case scancode::power:
                return os << "power";
            case scancode::execute:
                return os << "execute";
            case scancode::help:
                return os << "help";
            case scancode::menu:
                return os << "menu";
            case scancode::select:
                return os << "select";
            case scancode::stop:
                return os << "stop";
            case scancode::again:
                return os << "again";
            case scancode::undo:
                return os << "undo";
            case scancode::cut:
                return os << "cut";
            case scancode::copy:
                return os << "copy";
            case scancode::paste:
                return os << "paste";
            case scancode::find:
                return os << "find";
            case scancode::mute:
                return os << "mute";
            case scancode::volumeup:
                return os << "volumeup";
            case scancode::volumedown:
                return os << "volumedown";
            case scancode::count:
                return os << "count";
            default:
                return os << "Unknown_scancode(" << static_cast <int>(value) << ")";
        }
    }

    namespace {
        const std::unordered_map<std::string, scancode>& get_scancode_map() {
            static const std::unordered_map<std::string, scancode> map = {
                {"unknown", scancode::unknown},
                {"a", scancode::a}, {"b", scancode::b}, {"c", scancode::c},
                {"d", scancode::d}, {"e", scancode::e}, {"f", scancode::f},
                {"g", scancode::g}, {"h", scancode::h}, {"i", scancode::i},
                {"j", scancode::j}, {"k", scancode::k}, {"l", scancode::l},
                {"m", scancode::m}, {"n", scancode::n}, {"o", scancode::o},
                {"p", scancode::p}, {"q", scancode::q}, {"r", scancode::r},
                {"s", scancode::s}, {"t", scancode::t}, {"u", scancode::u},
                {"v", scancode::v}, {"w", scancode::w}, {"x", scancode::x},
                {"y", scancode::y}, {"z", scancode::z},
                {"num_1", scancode::num_1}, {"num_2", scancode::num_2},
                {"num_3", scancode::num_3}, {"num_4", scancode::num_4},
                {"num_5", scancode::num_5}, {"num_6", scancode::num_6},
                {"num_7", scancode::num_7}, {"num_8", scancode::num_8},
                {"num_9", scancode::num_9}, {"num_0", scancode::num_0},
                {"f1", scancode::f1}, {"f2", scancode::f2}, {"f3", scancode::f3},
                {"f4", scancode::f4}, {"f5", scancode::f5}, {"f6", scancode::f6},
                {"f7", scancode::f7}, {"f8", scancode::f8}, {"f9", scancode::f9},
                {"f10", scancode::f10}, {"f11", scancode::f11}, {"f12", scancode::f12},
                {"f13", scancode::f13}, {"f14", scancode::f14}, {"f15", scancode::f15},
                {"f16", scancode::f16}, {"f17", scancode::f17}, {"f18", scancode::f18},
                {"f19", scancode::f19}, {"f20", scancode::f20}, {"f21", scancode::f21},
                {"f22", scancode::f22}, {"f23", scancode::f23}, {"f24", scancode::f24},
                {"return_key", scancode::return_key}, {"escape", scancode::escape},
                {"backspace", scancode::backspace}, {"tab", scancode::tab},
                {"space", scancode::space}, {"minus", scancode::minus},
                {"equals", scancode::equals}, {"leftbracket", scancode::leftbracket},
                {"rightbracket", scancode::rightbracket}, {"backslash", scancode::backslash},
                {"nonushash", scancode::nonushash}, {"semicolon", scancode::semicolon},
                {"apostrophe", scancode::apostrophe}, {"grave", scancode::grave},
                {"comma", scancode::comma}, {"period", scancode::period},
                {"slash", scancode::slash}, {"capslock", scancode::capslock},
                {"scrolllock", scancode::scrolllock}, {"numlockclear", scancode::numlockclear},
                {"printscreen", scancode::printscreen}, {"pause", scancode::pause},
                {"insert", scancode::insert}, {"home", scancode::home},
                {"pageup", scancode::pageup}, {"delete_key", scancode::delete_key},
                {"end", scancode::end}, {"pagedown", scancode::pagedown},
                {"right", scancode::right}, {"left", scancode::left},
                {"down", scancode::down}, {"up", scancode::up},
                {"kp_divide", scancode::kp_divide}, {"kp_multiply", scancode::kp_multiply},
                {"kp_minus", scancode::kp_minus}, {"kp_plus", scancode::kp_plus},
                {"kp_enter", scancode::kp_enter},
                {"kp_1", scancode::kp_1}, {"kp_2", scancode::kp_2},
                {"kp_3", scancode::kp_3}, {"kp_4", scancode::kp_4},
                {"kp_5", scancode::kp_5}, {"kp_6", scancode::kp_6},
                {"kp_7", scancode::kp_7}, {"kp_8", scancode::kp_8},
                {"kp_9", scancode::kp_9}, {"kp_0", scancode::kp_0},
                {"kp_period", scancode::kp_period},
                {"lctrl", scancode::lctrl}, {"lshift", scancode::lshift},
                {"lalt", scancode::lalt}, {"lgui", scancode::lgui},
                {"rctrl", scancode::rctrl}, {"rshift", scancode::rshift},
                {"ralt", scancode::ralt}, {"rgui", scancode::rgui},
                {"application", scancode::application}, {"power", scancode::power},
                {"execute", scancode::execute}, {"help", scancode::help},
                {"menu", scancode::menu}, {"select", scancode::select},
                {"stop", scancode::stop}, {"again", scancode::again},
                {"undo", scancode::undo}, {"cut", scancode::cut},
                {"copy", scancode::copy}, {"paste", scancode::paste},
                {"find", scancode::find}, {"mute", scancode::mute},
                {"volumeup", scancode::volumeup}, {"volumedown", scancode::volumedown},
                {"count", scancode::count}
            };
            return map;
        }
    }

    std::istream& operator>>(std::istream& is, scancode& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast<scancode>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        // Use lookup table for O(1) lookup instead of O(n) if-else chain
        const auto& map = get_scancode_map();
        auto it = map.find(str);
        if (it != map.end()) {
            value = it->second;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast<scancode>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }

    std::ostream& operator<<(std::ostream& os, keymod value) {
        // Check if hex output is requested
        if (os.flags() & std::ios::hex) {
            // Output as hex value
            os << static_cast <unsigned int>(value);
            return os;
        }

        // Output as human-readable flag names
        std::vector <std::string> active_flags;

        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::none)) != 0) {
            active_flags.emplace_back("none");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::lshift)) != 0) {
            active_flags.emplace_back("lshift");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::rshift)) != 0) {
            active_flags.emplace_back("rshift");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::lctrl)) != 0) {
            active_flags.emplace_back("lctrl");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::rctrl)) != 0) {
            active_flags.emplace_back("rctrl");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::lalt)) != 0) {
            active_flags.emplace_back("lalt");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::ralt)) != 0) {
            active_flags.emplace_back("ralt");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::lgui)) != 0) {
            active_flags.emplace_back("lgui");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::rgui)) != 0) {
            active_flags.emplace_back("rgui");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::num)) != 0) {
            active_flags.emplace_back("num");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::caps)) != 0) {
            active_flags.emplace_back("caps");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::mode)) != 0) {
            active_flags.emplace_back("mode");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::scroll)) != 0) {
            active_flags.emplace_back("scroll");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::ctrl)) != 0) {
            active_flags.emplace_back("ctrl");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::shift)) != 0) {
            active_flags.emplace_back("shift");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::alt)) != 0) {
            active_flags.emplace_back("alt");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(keymod::gui)) != 0) {
            active_flags.emplace_back("gui");
        }

        // Sort flags lexicographically
        std::sort(active_flags.begin(), active_flags.end());

        if (active_flags.empty()) {
            os << "none";
        } else {
            bool first = true;
            for (const auto& flag : active_flags) {
                if (!first) os << " | ";
                os << flag;
                first = false;
            }
        }
        return os;
    }

    std::istream& operator>>(std::istream& is, keymod& value) {
        std::string str;
        is >> str;

        value = static_cast <keymod>(0);

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <keymod>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Check for explicit hex format (0x...)
        if (str.substr(0, 2) == "0x" || str.substr(0, 2) == "0X") {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <keymod>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Parse as flag names separated by |
        size_t start = 0;
        size_t pos = 0;

        while (start < str.length()) {
            pos = str.find('|', start);
            std::string flag_name = (pos == std::string::npos) ? str.substr(start) : str.substr(start, pos - start);

            // Trim whitespace
            size_t first = flag_name.find_first_not_of(' ');
            size_t last = flag_name.find_last_not_of(' ');
            if (first != std::string::npos && last != std::string::npos) {
                flag_name = flag_name.substr(first, last - first + 1);
            }

            // Convert to lowercase
            std::transform(flag_name.begin(), flag_name.end(), flag_name.begin(), ::tolower);

            // Match flag name
            bool found = false;
            if (flag_name == "none") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::none));
                found = true;
            }
            if (flag_name == "lshift") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::lshift));
                found = true;
            }
            if (flag_name == "rshift") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::rshift));
                found = true;
            }
            if (flag_name == "lctrl") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::lctrl));
                found = true;
            }
            if (flag_name == "rctrl") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::rctrl));
                found = true;
            }
            if (flag_name == "lalt") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::lalt));
                found = true;
            }
            if (flag_name == "ralt") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::ralt));
                found = true;
            }
            if (flag_name == "lgui") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::lgui));
                found = true;
            }
            if (flag_name == "rgui") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::rgui));
                found = true;
            }
            if (flag_name == "num") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::num));
                found = true;
            }
            if (flag_name == "caps") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::caps));
                found = true;
            }
            if (flag_name == "mode") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::mode));
                found = true;
            }
            if (flag_name == "scroll") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::scroll));
                found = true;
            }
            if (flag_name == "ctrl") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::ctrl));
                found = true;
            }
            if (flag_name == "shift") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::shift));
                found = true;
            }
            if (flag_name == "alt") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::alt));
                found = true;
            }
            if (flag_name == "gui") {
                value = static_cast <keymod>(static_cast <unsigned int>(value) | static_cast <unsigned int>(
                                                 keymod::gui));
                found = true;
            }

            if (!found) {
                // Try to parse as integer
                try {
                    unsigned int int_value = static_cast<unsigned int>(std::stoul(flag_name));
                    value = static_cast <keymod>(static_cast <unsigned int>(value) | int_value);
                } catch (...) {
                    is.setstate(std::ios::failbit);
                    return is;
                }
            }

            if (pos == std::string::npos) break;
            start = pos + 1;
        }

        return is;
    }
} // namespace
