/**
 * @file mouse_codes.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/events/mouse_codes.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <vector>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, mouse_button value) {
        switch (value) {
            case mouse_button::left:
                return os << "left";
            case mouse_button::middle:
                return os << "middle";
            case mouse_button::right:
                return os << "right";
            case mouse_button::x1:
                return os << "x1";
            case mouse_button::x2:
                return os << "x2";
            default:
                return os << "Unknown_mouse_button(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, mouse_button& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <mouse_button>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "left") {
            value = mouse_button::left;
        } else if (str == "middle") {
            value = mouse_button::middle;
        } else if (str == "right") {
            value = mouse_button::right;
        } else if (str == "x1") {
            value = mouse_button::x1;
        } else if (str == "x2") {
            value = mouse_button::x2;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <mouse_button>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }

    std::ostream& operator<<(std::ostream& os, mouse_button_mask value) {
        // Check if hex output is requested
        if (os.flags() & std::ios::hex) {
            // Output as hex value
            os << static_cast <unsigned int>(value);
            return os;
        }

        // Output as human-readable flag names
        std::vector <std::string> active_flags;

        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(mouse_button_mask::left)) != 0) {
            active_flags.emplace_back("left");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(mouse_button_mask::middle)) != 0) {
            active_flags.emplace_back("middle");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(mouse_button_mask::right)) != 0) {
            active_flags.emplace_back("right");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(mouse_button_mask::x1)) != 0) {
            active_flags.emplace_back("x1");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(mouse_button_mask::x2)) != 0) {
            active_flags.emplace_back("x2");
        }

        // Sort flags lexicographically
        std::sort(active_flags.begin(), active_flags.end());

        if (active_flags.empty()) {
            os << "none";
        } else {
            bool first = true;
            for (const auto& flag : active_flags) {
                if (!first) os << " | ";
                os << flag;
                first = false;
            }
        }
        return os;
    }

    std::istream& operator>>(std::istream& is, mouse_button_mask& value) {
        std::string str;
        // For flag enums, we need to read the entire content which may contain spaces
        // Read until newline or EOF to support "flag1 | flag2" format
        std::getline(is, str);

        value = static_cast <mouse_button_mask>(0);

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <mouse_button_mask>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Check for explicit hex format (0x...)
        if (str.substr(0, 2) == "0x" || str.substr(0, 2) == "0X") {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <mouse_button_mask>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Parse as flag names separated by |
        size_t start = 0;
        size_t pos = 0;

        while (start < str.length()) {
            pos = str.find('|', start);
            std::string flag_name = (pos == std::string::npos) ? str.substr(start) : str.substr(start, pos - start);

            // Trim whitespace
            size_t first = flag_name.find_first_not_of(' ');
            size_t last = flag_name.find_last_not_of(' ');
            if (first != std::string::npos && last != std::string::npos) {
                flag_name = flag_name.substr(first, last - first + 1);
            }

            // Convert to lowercase
            std::transform(flag_name.begin(), flag_name.end(), flag_name.begin(), ::tolower);

            // Match flag name
            bool found = false;
            if (flag_name == "none") {
                value = static_cast <mouse_button_mask>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(mouse_button_mask::none));
                found = true;
            }
            if (flag_name == "left") {
                value = static_cast <mouse_button_mask>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(mouse_button_mask::left));
                found = true;
            }
            if (flag_name == "middle") {
                value = static_cast <mouse_button_mask>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(mouse_button_mask::middle));
                found = true;
            }
            if (flag_name == "right") {
                value = static_cast <mouse_button_mask>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(mouse_button_mask::right));
                found = true;
            }
            if (flag_name == "x1") {
                value = static_cast <mouse_button_mask>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(mouse_button_mask::x1));
                found = true;
            }
            if (flag_name == "x2") {
                value = static_cast <mouse_button_mask>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(mouse_button_mask::x2));
                found = true;
            }

            if (!found) {
                // Try to parse as integer
                try {
                    unsigned int int_value = static_cast<unsigned int>(std::stoul(flag_name));
                    value = static_cast <mouse_button_mask>(static_cast <unsigned int>(value) | int_value);
                } catch (...) {
                    is.setstate(std::ios::failbit);
                    return is;
                }
            }

            if (pos == std::string::npos) break;
            start = pos + 1;
        }

        return is;
    }

    std::ostream& operator<<(std::ostream& os, mouse_wheel_direction value) {
        switch (value) {
            case mouse_wheel_direction::normal:
                return os << "normal";
            case mouse_wheel_direction::flipped:
                return os << "flipped";
            default:
                return os << "Unknown_mouse_wheel_direction(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, mouse_wheel_direction& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <mouse_wheel_direction>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "normal") {
            value = mouse_wheel_direction::normal;
        } else if (str == "flipped") {
            value = mouse_wheel_direction::flipped;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <mouse_wheel_direction>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
