/**
 * @file pen.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/input/pen.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <vector>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, pen_input_flags value) {
        // Check if hex output is requested
        if (os.flags() & std::ios::hex) {
            // Output as hex value
            os << static_cast <unsigned int>(value);
            return os;
        }

        // Output as human-readable flag names
        std::vector <std::string> active_flags;

        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(pen_input_flags::down)) != 0) {
            active_flags.emplace_back("down");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(pen_input_flags::button_1)) != 0) {
            active_flags.emplace_back("button_1");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(pen_input_flags::button_2)) != 0) {
            active_flags.emplace_back("button_2");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(pen_input_flags::button_3)) != 0) {
            active_flags.emplace_back("button_3");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(pen_input_flags::button_4)) != 0) {
            active_flags.emplace_back("button_4");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(pen_input_flags::button_5)) != 0) {
            active_flags.emplace_back("button_5");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(pen_input_flags::eraser_tip)) != 0) {
            active_flags.emplace_back("eraser_tip");
        }

        // Sort flags lexicographically
        std::sort(active_flags.begin(), active_flags.end());

        if (active_flags.empty()) {
            os << "none";
        } else {
            bool first = true;
            for (const auto& flag : active_flags) {
                if (!first) os << " | ";
                os << flag;
                first = false;
            }
        }
        return os;
    }

    std::istream& operator>>(std::istream& is, pen_input_flags& value) {
        std::string str;
        is >> str;

        value = static_cast <pen_input_flags>(0);

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <pen_input_flags>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Check for explicit hex format (0x...)
        if (str.substr(0, 2) == "0x" || str.substr(0, 2) == "0X") {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <pen_input_flags>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Parse as flag names separated by |
        size_t start = 0;
        size_t pos = 0;

        while (start < str.length()) {
            pos = str.find('|', start);
            std::string flag_name = (pos == std::string::npos) ? str.substr(start) : str.substr(start, pos - start);

            // Trim whitespace
            size_t first = flag_name.find_first_not_of(' ');
            size_t last = flag_name.find_last_not_of(' ');
            if (first != std::string::npos && last != std::string::npos) {
                flag_name = flag_name.substr(first, last - first + 1);
            }

            // Convert to lowercase
            std::transform(flag_name.begin(), flag_name.end(), flag_name.begin(), ::tolower);

            // Match flag name
            bool found = false;
            if (flag_name == "none") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::none));
                found = true;
            }
            if (flag_name == "down") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::down));
                found = true;
            }
            if (flag_name == "button_1") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::button_1));
                found = true;
            }
            if (flag_name == "button_2") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::button_2));
                found = true;
            }
            if (flag_name == "button_3") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::button_3));
                found = true;
            }
            if (flag_name == "button_4") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::button_4));
                found = true;
            }
            if (flag_name == "button_5") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::button_5));
                found = true;
            }
            if (flag_name == "eraser_tip") {
                value = static_cast <pen_input_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(pen_input_flags::eraser_tip));
                found = true;
            }

            if (!found) {
                // Try to parse as integer
                try {
                    unsigned int int_value = static_cast<unsigned int>(std::stoul(flag_name));
                    value = static_cast <pen_input_flags>(static_cast <unsigned int>(value) | int_value);
                } catch (...) {
                    is.setstate(std::ios::failbit);
                    return is;
                }
            }

            if (pos == std::string::npos) break;
            start = pos + 1;
        }

        return is;
    }

    std::ostream& operator<<(std::ostream& os, pen_axis value) {
        switch (value) {
            case pen_axis::pressure:
                return os << "pressure";
            case pen_axis::xtilt:
                return os << "xtilt";
            case pen_axis::ytilt:
                return os << "ytilt";
            case pen_axis::distance:
                return os << "distance";
            case pen_axis::rotation:
                return os << "rotation";
            case pen_axis::slider:
                return os << "slider";
            case pen_axis::tangential_pressure:
                return os << "tangential_pressure";
            case pen_axis::count:
                return os << "count";
            default:
                return os << "Unknown_pen_axis(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, pen_axis& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <pen_axis>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "pressure") {
            value = pen_axis::pressure;
        } else if (str == "xtilt") {
            value = pen_axis::xtilt;
        } else if (str == "ytilt") {
            value = pen_axis::ytilt;
        } else if (str == "distance") {
            value = pen_axis::distance;
        } else if (str == "rotation") {
            value = pen_axis::rotation;
        } else if (str == "slider") {
            value = pen_axis::slider;
        } else if (str == "tangential_pressure") {
            value = pen_axis::tangential_pressure;
        } else if (str == "count") {
            value = pen_axis::count;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <pen_axis>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
