/**
 * @file sensor.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/input/sensor.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, sensor_type value) {
        switch (value) {
            case sensor_type::invalid:
                return os << "invalid";
            case sensor_type::unknown:
                return os << "unknown";
            case sensor_type::accel:
                return os << "accel";
            case sensor_type::gyro:
                return os << "gyro";
            case sensor_type::accel_l:
                return os << "accel_l";
            case sensor_type::gyro_l:
                return os << "gyro_l";
            case sensor_type::accel_r:
                return os << "accel_r";
            case sensor_type::gyro_r:
                return os << "gyro_r";
            default:
                return os << "Unknown_sensor_type(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, sensor_type& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <sensor_type>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "invalid") {
            value = sensor_type::invalid;
        } else if (str == "unknown") {
            value = sensor_type::unknown;
        } else if (str == "accel") {
            value = sensor_type::accel;
        } else if (str == "gyro") {
            value = sensor_type::gyro;
        } else if (str == "accel_l") {
            value = sensor_type::accel_l;
        } else if (str == "gyro_l") {
            value = sensor_type::gyro_l;
        } else if (str == "accel_r") {
            value = sensor_type::accel_r;
        } else if (str == "gyro_r") {
            value = sensor_type::gyro_r;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <sensor_type>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
