/**
 * @file touch.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/input/touch.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, touch_device_type value) {
        switch (value) {
            case touch_device_type::invalid:
                return os << "invalid";
            case touch_device_type::direct:
                return os << "direct";
            case touch_device_type::indirect_absolute:
                return os << "indirect_absolute";
            case touch_device_type::indirect_relative:
                return os << "indirect_relative";
            default:
                return os << "Unknown_touch_device_type(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, touch_device_type& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <touch_device_type>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "invalid") {
            value = touch_device_type::invalid;
        } else if (str == "direct") {
            value = touch_device_type::direct;
        } else if (str == "indirect_absolute") {
            value = touch_device_type::indirect_absolute;
        } else if (str == "indirect_relative") {
            value = touch_device_type::indirect_relative;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <touch_device_type>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
