/**
 * @file dialog.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/ui/dialog.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <vector>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, file_dialog_type value) {
        switch (value) {
            case file_dialog_type::open_file:
                return os << "open_file";
            case file_dialog_type::save_file:
                return os << "save_file";
            case file_dialog_type::open_folder:
                return os << "open_folder";
            default:
                return os << "Unknown_file_dialog_type(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, file_dialog_type& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <file_dialog_type>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "open_file") {
            value = file_dialog_type::open_file;
        } else if (str == "save_file") {
            value = file_dialog_type::save_file;
        } else if (str == "open_folder") {
            value = file_dialog_type::open_folder;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <file_dialog_type>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
