/**
 * @file tray.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/ui/tray.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>
#include <vector>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, tray_entry_flags value) {
        // Check if hex output is requested
        if (os.flags() & std::ios::hex) {
            // Output as hex value
            os << static_cast <unsigned int>(value);
            return os;
        }

        // Output as human-readable flag names
        std::vector <std::string> active_flags;

        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(tray_entry_flags::checked)) != 0) {
            active_flags.emplace_back("checked");
        }
        if ((static_cast <unsigned int>(value) & static_cast <unsigned int>(tray_entry_flags::disabled)) != 0) {
            active_flags.emplace_back("disabled");
        }

        // Sort flags lexicographically
        std::sort(active_flags.begin(), active_flags.end());

        if (active_flags.empty()) {
            os << "none";
        } else {
            bool first = true;
            for (const auto& flag : active_flags) {
                if (!first) os << " | ";
                os << flag;
                first = false;
            }
        }
        return os;
    }

    std::istream& operator>>(std::istream& is, tray_entry_flags& value) {
        std::string str;
        // For flag enums, we need to read the entire content which may contain spaces
        // Read until newline or EOF to support "flag1 | flag2" format
        std::getline(is, str);

        value = static_cast <tray_entry_flags>(0);

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <tray_entry_flags>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Check for explicit hex format (0x...)
        if (str.substr(0, 2) == "0x" || str.substr(0, 2) == "0X") {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <tray_entry_flags>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Parse as flag names separated by |
        size_t start = 0;
        size_t pos = 0;

        while (start < str.length()) {
            pos = str.find('|', start);
            std::string flag_name = (pos == std::string::npos) ? str.substr(start) : str.substr(start, pos - start);

            // Trim whitespace
            size_t first = flag_name.find_first_not_of(' ');
            size_t last = flag_name.find_last_not_of(' ');
            if (first != std::string::npos && last != std::string::npos) {
                flag_name = flag_name.substr(first, last - first + 1);
            }

            // Convert to lowercase
            std::transform(flag_name.begin(), flag_name.end(), flag_name.begin(), ::tolower);

            // Match flag name
            bool found = false;
            if (flag_name == "none") {
                value = static_cast <tray_entry_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(tray_entry_flags::none));
                found = true;
            }
            if (flag_name == "checked") {
                value = static_cast <tray_entry_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(tray_entry_flags::checked));
                found = true;
            }
            if (flag_name == "disabled") {
                value = static_cast <tray_entry_flags>(
                    static_cast <unsigned int>(value) | static_cast <unsigned int>(tray_entry_flags::disabled));
                found = true;
            }

            if (!found) {
                // Try to parse as integer
                try {
                    unsigned int int_value = static_cast<unsigned int>(std::stoul(flag_name));
                    value = static_cast <tray_entry_flags>(static_cast <unsigned int>(value) | int_value);
                } catch (...) {
                    is.setstate(std::ios::failbit);
                    return is;
                }
            }

            if (pos == std::string::npos) break;
            start = pos + 1;
        }

        return is;
    }
} // namespace
