/**
 * @file power_state.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/system/power_state.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, power_state value) {
        switch (value) {
            case power_state::error:
                return os << "error";
            case power_state::unknown:
                return os << "unknown";
            case power_state::on_battery:
                return os << "on_battery";
            case power_state::no_battery:
                return os << "no_battery";
            case power_state::charging:
                return os << "charging";
            case power_state::charged:
                return os << "charged";
            default:
                return os << "Unknown_power_state(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, power_state& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <power_state>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "error") {
            value = power_state::error;
        } else if (str == "unknown") {
            value = power_state::unknown;
        } else if (str == "on_battery") {
            value = power_state::on_battery;
        } else if (str == "no_battery") {
            value = power_state::no_battery;
        } else if (str == "charging") {
            value = power_state::charging;
        } else if (str == "charged") {
            value = power_state::charged;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <power_state>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
