/**
 * @file test_audio_enum_operators.cc
 * @brief Unit tests for enum stream operators
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <doctest/doctest.h>
#include <sdlpp/audio/audio.hh>
#include <sstream>
#include <string>

TEST_SUITE("audio_enum_operators") {

    TEST_CASE("audio_format stream operators") {
        SUBCASE("operator<< outputs correct string representation") {
            std::ostringstream oss;
            oss << sdlpp::audio_format::unknown;
            CHECK(oss.str() == "unknown");
            oss.str("");
            oss << sdlpp::audio_format::u8;
            CHECK(oss.str() == "u8");
            oss.str("");
            oss << sdlpp::audio_format::s8;
            CHECK(oss.str() == "s8");
            oss.str("");
        }

        SUBCASE("operator>> parses string correctly") {
            std::istringstream iss;
            sdlpp::audio_format value;
            iss.str("unknown");
            iss >> value;
            CHECK(value == sdlpp::audio_format::unknown);
            iss.clear();
            iss.str("u8");
            iss >> value;
            CHECK(value == sdlpp::audio_format::u8);
            iss.clear();
            iss.str("s8");
            iss >> value;
            CHECK(value == sdlpp::audio_format::s8);
            iss.clear();

            // Test integer parsing
            iss.str("0");
            iss >> value;
            CHECK(static_cast<int>(value) == 0);
        }

        SUBCASE("round-trip conversion works") {
            std::stringstream ss;
            sdlpp::audio_format original = sdlpp::audio_format::unknown;
            sdlpp::audio_format result;

            ss << original;
            ss >> result;

            CHECK(result == original);
        }
    }
}