/**
 * @file test_video_enum_operators.cc
 * @brief Unit tests for enum stream operators
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <doctest/doctest.h>
#include <sdlpp/video/window.hh>
#include <sstream>
#include <string>

TEST_SUITE("video_enum_operators") {

    TEST_CASE("window_flags stream operators") {
        SUBCASE("operator<< outputs correct string representation") {
            std::ostringstream oss;
            oss << static_cast<sdlpp::window_flags>(0);
            CHECK(oss.str() == "none");
            oss.str("");
            oss << std::hex << static_cast<sdlpp::window_flags>(0x5) << std::dec;
            CHECK(oss.str() == "5");
            oss.str("");
        }

        SUBCASE("operator>> parses string correctly") {
            std::istringstream iss;
            sdlpp::window_flags value;
            iss.str("fullscreen");
            iss >> value;
            CHECK(value == sdlpp::window_flags::fullscreen);
            iss.clear();
            iss.str("opengl");
            iss >> value;
            CHECK(value == sdlpp::window_flags::opengl);
            iss.clear();

            // Test parsing multiple flags
            iss.str("fullscreen | opengl");
            iss >> value;
            CHECK((static_cast<unsigned int>(value) & static_cast<unsigned int>(sdlpp::window_flags::fullscreen)) != 0);
            CHECK((static_cast<unsigned int>(value) & static_cast<unsigned int>(sdlpp::window_flags::opengl)) != 0);
            iss.clear();

            // Test hex parsing with 0x prefix
            iss.str("0xFF");
            iss >> value;
            CHECK(static_cast<unsigned int>(value) == 0xFF);
            iss.clear();

            // Test hex parsing with stream flag
            iss.str("FF");
            iss >> std::hex >> value >> std::dec;
            CHECK(static_cast<unsigned int>(value) == 0xFF);
        }

        SUBCASE("round-trip conversion works") {
            // Flags enum - test with multiple flags
            std::stringstream ss;
            sdlpp::window_flags original = static_cast<sdlpp::window_flags>(
                static_cast<unsigned int>(sdlpp::window_flags::fullscreen) |
                static_cast<unsigned int>(sdlpp::window_flags::opengl)
            );


            // Output will be human-readable flag names
            ss << original;
            std::string output = ss.str();
            CHECK(output.find("fullscreen") != std::string::npos);
            CHECK(output.find("opengl") != std::string::npos);
            CHECK(output.find(" | ") != std::string::npos);
        }
    }

    TEST_CASE("fullscreen_mode stream operators") {
        SUBCASE("operator<< outputs correct string representation") {
            std::ostringstream oss;
            oss << sdlpp::fullscreen_mode::windowed;
            CHECK(oss.str() == "windowed");
            oss.str("");
            oss << sdlpp::fullscreen_mode::fullscreen;
            CHECK(oss.str() == "fullscreen");
            oss.str("");
        }

        SUBCASE("operator>> parses string correctly") {
            std::istringstream iss;
            sdlpp::fullscreen_mode value;
            iss.str("windowed");
            iss >> value;
            CHECK(value == sdlpp::fullscreen_mode::windowed);
            iss.clear();
            iss.str("fullscreen");
            iss >> value;
            CHECK(value == sdlpp::fullscreen_mode::fullscreen);
            iss.clear();

            // Test integer parsing
            iss.str("0");
            iss >> value;
            CHECK(static_cast<int>(value) == 0);
        }

        SUBCASE("round-trip conversion works") {
            std::stringstream ss;
            sdlpp::fullscreen_mode original = sdlpp::fullscreen_mode::windowed;
            sdlpp::fullscreen_mode result;

            ss << original;
            ss >> result;

            CHECK(result == original);
        }
    }
}