macro(add_simplex_example name)
    add_executable(${name} ${name}.cc)
    target_link_libraries(${name} PRIVATE simplex)
    target_compile_options(${name} PRIVATE ${SDLPP_WARNING_FLAGS})
endmacro()

add_simplex_example(example_simplex)
add_simplex_example(example_collision)
add_simplex_example(example_animation)
add_simplex_example(example_fire)
add_simplex_example(example_circle_physics)