/**
 * @file renderer.cc
 * @brief Stream operator implementations for enums
 * @note This file is auto-generated by generate_enum_operators.py
 */

#include <sdlpp/video/renderer.hh>
#include <iostream>
#include <string>
#include <algorithm>
#include <cctype>

namespace sdlpp {
    std::ostream& operator<<(std::ostream& os, texture_access value) {
        switch (value) {
            case texture_access::static_access:
                return os << "static_access";
            case texture_access::streaming:
                return os << "streaming";
            case texture_access::target:
                return os << "target";
            default:
                return os << "Unknown_texture_access(" << static_cast <int>(value) << ")";
        }
    }

    std::istream& operator>>(std::istream& is, texture_access& value) {
        std::string str;
        is >> str;

        // Check if hex input is expected based on stream flags
        if (is.flags() & std::ios::hex) {
            try {
                unsigned int int_value = static_cast<unsigned int>(std::stoul(str, nullptr, 16));
                value = static_cast <texture_access>(int_value);
                return is;
            } catch (...) {
                is.setstate(std::ios::failbit);
                return is;
            }
        }

        // Convert to lowercase for case-insensitive comparison
        std::transform(str.begin(), str.end(), str.begin(), ::tolower);

        if (str == "static_access") {
            value = texture_access::static_access;
        } else if (str == "streaming") {
            value = texture_access::streaming;
        } else if (str == "target") {
            value = texture_access::target;
        } else {
            // Try to parse as integer
            try {
                int int_value = std::stoi(str);
                value = static_cast <texture_access>(int_value);
            } catch (...) {
                is.setstate(std::ios::failbit);
            }
        }

        return is;
    }
} // namespace
